-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
INSERT INTO table1 (sp1,sp2)
VALUES ('','S1, S2, S3, S4, S5');
INSERT INTO table1 (sp1,sp2)
VALUES ('A','A1, A2, A3, A4, A5');
INSERT INTO table1 (sp1,sp2)
VALUES ('B','B1, B2, B3, B4, B5');
INSERT INTO table1 (sp1,sp2)
VALUES ('C','C1, C2, C3, C4, C5');
INSERT INTO table1 (sp1,sp2)
VALUES ('D','D1, D2, D3, D4, D5');
COMMIT;
-- 25 ;
-- Output on yyyy-mm-dd hh:mm:ss by Dbat script test/aggr01, Excel, more
--
