java -cp ../dist/dbat.jar org.teherba.dbat.Dbat -c ../etc/worddb.properties -e UTF-8 -d b01
-- SQL generated by Dbat at 2011-11-16T22:30:21
-- MySQL 5.1.54-1ubuntu4 with MySQL-AB JDBC Driver mysql-connector-java-5.1.11 ( Revision: ${svn.Revision} )
DROP   TABLE b01;
CREATE TABLE b01
	( name	VARCHAR(16) NOT NULL
	, content	BLOB
	);
COMMIT;
-- finished at 2011-11-16T22:30:21
