-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
-- MySQL with MySQL-AB JDBC Driver
DROP   TABLE b04;
CREATE TABLE b04
	( name	VARCHAR(16) NOT NULL -- key for the LOB
	, len	INT -- size of the LOB content
	, content	TEXT -- character large object (CLOB)
	);
COMMIT;
