java -cp ../dist/dbat.jar org.teherba.dbat.Dbat -c ../etc/worddb.properties -e UTF-8 -m sql -o commit=2 -100 c01
-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Martha','Freiburg',1999,'&','1909-11-17');
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Johannes','Schramberg',1992,'<','1911-06-03');
-- 2;
COMMIT;
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Eberhard','Groß-Gerau',1945,'>','1912-11-17');
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Fritz','Waldshut',1995,'<','1907-08-08');
-- 4;
COMMIT;
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Maria','Hermsdorf',1999,'#','1914-09-17');
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Ilse','Lübars',1983,'$','1909-02-09');
-- 6;
COMMIT;
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Dorothea','Lübars',1985,'$','1910-02-07');
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Lucie','Lübars',1984,'''','1887-07-09');
-- 8;
COMMIT;
COMMIT;
