--  Stored Procedure for test/crud02.xml (äöü)
--  @(#) $Id$
--  Generated by dbat/etc/xslt/dbiv_sproc.xsl V1.1 at 2012-06-25T18:31:59+02:00
DROP   PROCEDURE spr02 $
CREATE PROCEDURE spr02
    ( IN    opcode                  CHAR(3)
    --
    , IN    fp_name                 CHAR(40) -- key=1
    , IN    fp_family               CHAR(40) -- key=2
    , IN    fp_gender               CHAR(1) -- key=3
    , IN    fp_birth                CHAR(10)
    , IN    fp_place                CHAR(100)
    , IN    fp_decease              INT
    , IN    fp_user                 CHAR(8)
    )
BEGIN
    CASE opcode
    WHEN 'del' THEN 
        DELETE FROM relatives
        WHERE name                  = fp_name
          AND family                = fp_family
          AND gender                = fp_gender
        ;
        
    WHEN 'ins' THEN 
        INSERT INTO relatives
        ( name
        , family
        , gender
        , birth
        , place
        , decease
        , user
        , changed
        ) VALUES
        ( fp_name
        , fp_family
        , fp_gender
        , fp_birth
        , fp_place
        , fp_decease
        , fp_user
        , current_timestamp
        );
        
    WHEN 'upd' THEN 
        UPDATE relatives
          SET birth                 = fp_birth
            , place                 = fp_place
            , decease               = fp_decease
            , user                  = fp_user
            , changed               = current_timestamp
        WHERE name                  = fp_name
          AND family                = fp_family
          AND gender                = fp_gender
        ;
        
    END CASE;
END
$
