<?xml version="1.0" encoding="UTF-8"?>
<!--
    Dbat Specification generated by SpecDescription at yyyy-mm-dd hh:mm:ss
    @(#) $Id$
-->
<dbat
    xmlns   ="http://www.teherba.org/2007/dbat"
    xmlns:ht="http://www.w3.org/1999/xhtml"
    encoding="UTF-8"
    conn="worddb"
    lang="en"
    title="null"
    >
    <ht:h2>Table c01</ht:h2>
    <ht:form method="get">
        <ht:input label="Prefix" name="prefix" maxsize="20" size="10" />
        <ht:input type="submit" value="Submit" />
    </ht:form>

    <select>
        <col label="name">a.name</col>
        <col label="univ">a.univ</col>
        <col label="year" align="right">a.year</col>
        <col label="gender">a.gender</col>
        <col label="birth">a.birth</col>
        <from> c01 a
        </from>
        <where> name like '<parm name="prefix" />%'
        </where>
        <counter desc="Row,s" />
    </select>
</dbat>
