java -cp ../dist/dbat.jar org.teherba.dbat.Dbat -c ../etc/worddb.properties -e UTF-8 -f FK4.data.tmp
2012-04-17 10:31:08,917 1    [main] ERROR org.teherba.dbat.SQLAction  - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'if exists prodnx' at line 1
 com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'if exists prodnx' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1051)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3563)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3495)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2113)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2687)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1647)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1566)
	at org.teherba.dbat.SQLAction.execSQLStatement(SQLAction.java:1398)
	at org.teherba.dbat.SQLAction.execSQLfromURI(SQLAction.java:1507)
	at org.teherba.dbat.Dbat.process(Dbat.java:599)
	at org.teherba.dbat.Dbat.processArguments(Dbat.java:677)
	at org.teherba.dbat.Dbat.main(Dbat.java:697)
2012-04-17 10:31:08,921 5    [main] ERROR org.teherba.dbat.SQLAction  - Duplicate key name 'prodnx'
 com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate key name 'prodnx'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1051)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3563)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3495)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2113)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2687)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1647)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1566)
	at org.teherba.dbat.SQLAction.execSQLStatement(SQLAction.java:1398)
	at org.teherba.dbat.SQLAction.execSQLfromURI(SQLAction.java:1507)
	at org.teherba.dbat.Dbat.process(Dbat.java:599)
	at org.teherba.dbat.Dbat.processArguments(Dbat.java:677)
	at org.teherba.dbat.Dbat.main(Dbat.java:697)
2012-04-17 10:31:08,923 7    [main] ERROR org.teherba.dbat.SQLAction  - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'if exists produx' at line 1
 com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'if exists produx' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1051)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3563)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3495)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2113)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2687)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1647)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1566)
	at org.teherba.dbat.SQLAction.execSQLStatement(SQLAction.java:1398)
	at org.teherba.dbat.SQLAction.execSQLfromURI(SQLAction.java:1507)
	at org.teherba.dbat.Dbat.process(Dbat.java:599)
	at org.teherba.dbat.Dbat.processArguments(Dbat.java:677)
	at org.teherba.dbat.Dbat.main(Dbat.java:697)
2012-04-17 10:31:08,924 8    [main] ERROR org.teherba.dbat.SQLAction  - Duplicate key name 'produx'
 com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate key name 'produx'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1051)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3563)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3495)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1959)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2113)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2687)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1647)
	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1566)
	at org.teherba.dbat.SQLAction.execSQLStatement(SQLAction.java:1398)
	at org.teherba.dbat.SQLAction.execSQLfromURI(SQLAction.java:1507)
	at org.teherba.dbat.Dbat.process(Dbat.java:599)
	at org.teherba.dbat.Dbat.processArguments(Dbat.java:677)
	at org.teherba.dbat.Dbat.main(Dbat.java:697)
