-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('','c1','S1');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('','c2','S2');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('','c3','S3');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('','c4','S4');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('','c5','S5');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('A','c1','A1');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('A','c2','A2');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('A','c3','A3');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('A','c4','A4');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('A','c5','A5');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('B','c1','B1');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('B','c2','B2');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('B','c3','B3');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('B','c4','B4');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('B','c5','B5');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('C','c1','C1');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('C','c2','C2');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('C','c3','C3');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('C','c4','C4');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('C','c5','C5');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('D','c1','D1');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('D','c2','D2');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('D','c3','D3');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('D','c4','D4');
INSERT INTO table1 (sp1,sp2,sp3)
VALUES ('D','c5','D5');
-- 25 rows
COMMIT;
-- 25 ;
-- Output on yyyy-mm-dd hh:mm:ss by Dbat script test/grouping, Excel, more
--
