-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
INSERT INTO table_not_specified (name,birth)
VALUES ('Dorothea','1910-02-07');
INSERT INTO table_not_specified (name,birth)
VALUES ('Eberhard','1912-11-17');
INSERT INTO table_not_specified (name,birth)
VALUES ('Fritz',NULL);
INSERT INTO table_not_specified (name,birth)
VALUES ('Ilse',NULL);
INSERT INTO table_not_specified (name,birth)
VALUES ('Johannes','1911-06-03');
INSERT INTO table_not_specified (name,birth)
VALUES ('Lucie',NULL);
INSERT INTO table_not_specified (name,birth)
VALUES ('Maria','1914-09-17');
INSERT INTO table_not_specified (name,birth)
VALUES ('Martha','1909-11-17');
COMMIT;
-- 8 ;
