java -cp ../dist/dbat.jar org.teherba.dbat.Dbat -c ../etc/worddb.properties -e UTF-8 -m sql -f ../web/spec/test/selnull.xml -o null=0
-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
INSERT INTO table_not_specified (univ,display,lang)
VALUES ('Freiburg','male','eng');
INSERT INTO table_not_specified (univ,display,lang)
VALUES ('Schramberg',NULL,NULL);
INSERT INTO table_not_specified (univ,display,lang)
VALUES ('Groß-Gerau',NULL,NULL);
INSERT INTO table_not_specified (univ,display,lang)
VALUES ('Waldshut','female','eng');
INSERT INTO table_not_specified (univ,display,lang)
VALUES ('Hermsdorf','male','eng');
INSERT INTO table_not_specified (univ,display,lang)
VALUES ('Lübars',NULL,NULL);
INSERT INTO table_not_specified (univ,display,lang)
VALUES ('Lübars',NULL,NULL);
INSERT INTO table_not_specified (univ,display,lang)
VALUES ('Lübars',NULL,NULL);
COMMIT;
-- Output on yyyy-mm-dd hh:mm:ss by Dbat script ../web/spec/test/selnull.xml, Excel, more
--
