wget -q -O - "http://localhost:8080/dbat/servlet?spec=test/pivot03&mode=sql"
-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
INSERT INTO table_not_specified (sp1,sp3,sp3,sp3,sp3,sp3)
VALUES ('A','A1','A2','A3','A4','A5');
INSERT INTO table_not_specified (sp1,sp3,sp3,sp3,sp3,sp3)
VALUES ('B','B1','B2','B3','B4','B5');
INSERT INTO table_not_specified (sp1,sp3,sp3,sp3,sp3,sp3)
VALUES ('C','C1','C2','C3','C4','C5');
INSERT INTO table_not_specified (sp1,sp3,sp3,sp3,sp3,sp3)
VALUES ('D','D1','D2','D3','D4','D5');
COMMIT;
-- Output on yyyy-mm-dd hh:mm:ss by Dbat script test/pivot03, Excel, more
--
