-- SQL:
--select * from (
--SELECT concat(name, concat('*', cast(year as char)))
--, concat(cast(year as char), concat('=', name))
--, concat(cast(year as char), concat('=e.', cast(year as char)))
--, concat(name, concat('=f.', name))
--, univ
--, gender
--, birth 
--FROM c01 
--WHERE name like '%' 
--) probe where 1 = 0;
--:SQL
