java -cp ../dist/dbat.jar org.teherba.dbat.Dbat -c ../etc/worddb.properties -e UTF-8 -m jdbc -29 c01
-- SQL generated by Dbat at 2012-06-19 19:45:38
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Martha','Freiburg',1999,'&',{d'1909-11-17'});
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Johannes','Schramberg',1992,'<',{d'1911-06-03'});
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Eberhard','Groß-Gerau',1945,'>',{d'1912-11-17'});
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Fritz','Waldshut',1995,'<',{d'1907-08-08'});
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Maria','Hermsdorf',1999,'#',{d'1914-09-17'});
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Ilse','Lübars',1983,'$',{d'1909-02-09'});
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Dorothea','Lübars',1985,'$',{d'1910-02-07'});
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Lucie','Lübars',1984,'''',{d'1887-07-09'});
COMMIT;
