java -cp ../dist/dbat.jar org.teherba.dbat.Dbat -c ../etc/worddb.properties -e UTF-8 -m update -29 c01
-- SQL generated by Dbat at 2012-06-19 19:45:42
UPDATE c01 SET name='Martha',univ='Freiburg',year=1999,gender='&',birth
='1909-11-17'
WHERE name='Martha' AND univ='Freiburg' AND year=1999 AND gender='&'
 AND birth='1909-11-17';
UPDATE c01 SET name='Johannes',univ='Schramberg',year=1992,gender='<',
birth='1911-06-03'
WHERE name='Johannes' AND univ='Schramberg' AND year=1992 AND gender=
'<' AND birth='1911-06-03';
UPDATE c01 SET name='Eberhard',univ='Groß-Gerau',year=1945,gender='>',
birth='1912-11-17'
WHERE name='Eberhard' AND univ='Groß-Gerau' AND year=1945 AND gender=
'>' AND birth='1912-11-17';
UPDATE c01 SET name='Fritz',univ='Waldshut',year=1995,gender='<',birth=
'1907-08-08'
WHERE name='Fritz' AND univ='Waldshut' AND year=1995 AND gender='<'
 AND birth='1907-08-08';
UPDATE c01 SET name='Maria',univ='Hermsdorf',year=1999,gender='#',birth
='1914-09-17'
WHERE name='Maria' AND univ='Hermsdorf' AND year=1999 AND gender='#'
 AND birth='1914-09-17';
UPDATE c01 SET name='Ilse',univ='Lübars',year=1983,gender='$',birth=
'1909-02-09'
WHERE name='Ilse' AND univ='Lübars' AND year=1983 AND gender='$' AND 
birth='1909-02-09';
UPDATE c01 SET name='Dorothea',univ='Lübars',year=1985,gender='$',birth
='1910-02-07'
WHERE name='Dorothea' AND univ='Lübars' AND year=1985 AND gender='$'
 AND birth='1910-02-07';
UPDATE c01 SET name='Lucie',univ='Lübars',year=1984,gender='''',birth=
'1887-07-09'
WHERE name='Lucie' AND univ='Lübars' AND year=1984 AND gender='''' AND 
birth='1887-07-09';
COMMIT;
