java -cp ../dist/dbat.jar org.teherba.dbat.Dbat -c ../etc/worddb.properties -e UTF-8 -m jdbc -f ../web/spec/test/selec02.xml
-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
INSERT INTO table_not_specified (col0,col1,col2,col3,univ,gender,birth)
VALUES ('1999','Martha','e.1999','f.Martha','Freiburg','&',
{d'1909-11-17'});
INSERT INTO table_not_specified (col0,col1,col2,col3,univ,gender,birth)
VALUES ('1992','Johannes','e.1992','f.Johannes','Schramberg','<',
{d'1911-06-03'});
INSERT INTO table_not_specified (col0,col1,col2,col3,univ,gender,birth)
VALUES ('1945','Eberhard','e.1945','f.Eberhard','Groß-Gerau','>',
{d'1912-11-17'});
INSERT INTO table_not_specified (col0,col1,col2,col3,univ,gender,birth)
VALUES ('1995','Fritz','e.1995','f.Fritz','Waldshut','<',
{d'1907-08-08'});
INSERT INTO table_not_specified (col0,col1,col2,col3,univ,gender,birth)
VALUES ('1999','Maria','e.1999','f.Maria','Hermsdorf','#',
{d'1914-09-17'});
INSERT INTO table_not_specified (col0,col1,col2,col3,univ,gender,birth)
VALUES ('1983','Ilse','e.1983','f.Ilse','Lübars','$',{d'1909-02-09'});
INSERT INTO table_not_specified (col0,col1,col2,col3,univ,gender,birth)
VALUES ('1985','Dorothea','e.1985','f.Dorothea','Lübars','$',
{d'1910-02-07'});
INSERT INTO table_not_specified (col0,col1,col2,col3,univ,gender,birth)
VALUES ('1984','Lucie','e.1984','f.Lucie','Lübars','''',{d'1887-07-09'}
);
-- 8 persons
COMMIT;
-- Output on yyyy-mm-dd hh:mm:ss by Dbat script ../web/spec/test/selec02.xml, Excel, more
--
