-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
UPDATE table1 SET col0='1999',col1='Martha',col2='e.1999',col3=
'f.Martha',univ='Freiburg',gender='&',birth='1909-11-17'
WHERE col0='1999' AND col1='Martha' AND col2='e.1999' AND col3=
'f.Martha' AND univ='Freiburg' AND gender='&' AND birth='1909-11-17';
UPDATE table1 SET col0='1992',col1='Johannes',col2='e.1992',col3=
'f.Johannes',univ='Schramberg',gender='<',birth='1911-06-03'
WHERE col0='1992' AND col1='Johannes' AND col2='e.1992' AND col3=
'f.Johannes' AND univ='Schramberg' AND gender='<' AND birth=
'1911-06-03';
UPDATE table1 SET col0='1945',col1='Eberhard',col2='e.1945',col3=
'f.Eberhard',univ='Groß-Gerau',gender='>',birth='1912-11-17'
WHERE col0='1945' AND col1='Eberhard' AND col2='e.1945' AND col3=
'f.Eberhard' AND univ='Groß-Gerau' AND gender='>' AND birth=
'1912-11-17';
UPDATE table1 SET col0='1995',col1='Fritz',col2='e.1995',col3='f.Fritz'
,univ='Waldshut',gender='<',birth='1907-08-08'
WHERE col0='1995' AND col1='Fritz' AND col2='e.1995' AND col3='f.Fritz'
 AND univ='Waldshut' AND gender='<' AND birth='1907-08-08';
UPDATE table1 SET col0='1999',col1='Maria',col2='e.1999',col3='f.Maria'
,univ='Hermsdorf',gender='#',birth='1914-09-17'
WHERE col0='1999' AND col1='Maria' AND col2='e.1999' AND col3='f.Maria'
 AND univ='Hermsdorf' AND gender='#' AND birth='1914-09-17';
UPDATE table1 SET col0='1983',col1='Ilse',col2='e.1983',col3='f.Ilse',
univ='Lübars',gender='$',birth='1909-02-09'
WHERE col0='1983' AND col1='Ilse' AND col2='e.1983' AND col3='f.Ilse'
 AND univ='Lübars' AND gender='$' AND birth='1909-02-09';
UPDATE table1 SET col0='1985',col1='Dorothea',col2='e.1985',col3=
'f.Dorothea',univ='Lübars',gender='$',birth='1910-02-07'
WHERE col0='1985' AND col1='Dorothea' AND col2='e.1985' AND col3=
'f.Dorothea' AND univ='Lübars' AND gender='$' AND birth='1910-02-07';
UPDATE table1 SET col0='1984',col1='Lucie',col2='e.1984',col3='f.Lucie'
,univ='Lübars',gender='''',birth='1887-07-09'
WHERE col0='1984' AND col1='Lucie' AND col2='e.1984' AND col3='f.Lucie'
 AND univ='Lübars' AND gender='''' AND birth='1887-07-09';
-- 8 persons
COMMIT;
-- 8 ;
-- Output on yyyy-mm-dd hh:mm:ss by Dbat script web/spec/test/selec02.xml, Excel, more
--
