java -cp ../dist/dbat.jar org.teherba.dbat.Dbat -c ../etc/worddb.properties -e UTF-8 -m update -f ../web/spec/test/selec02.xml
-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
UPDATE table_not_specified SET Year='1999',Name='Martha',Year='e.1999',
Name='f.Martha',University='Freiburg',Gender='&',Birthdate='1909-11-17'
WHERE Year='1999' AND Name='Martha' AND Year='e.1999' AND Name=
'f.Martha' AND University='Freiburg' AND Gender='&' AND Birthdate=
'1909-11-17';
UPDATE table_not_specified SET Year='1992',Name='Johannes',Year=
'e.1992',Name='f.Johannes',University='Schramberg',Gender='<',Birthdate
='1911-06-03'
WHERE Year='1992' AND Name='Johannes' AND Year='e.1992' AND Name=
'f.Johannes' AND University='Schramberg' AND Gender='<' AND Birthdate=
'1911-06-03';
UPDATE table_not_specified SET Year='1945',Name='Eberhard',Year=
'e.1945',Name='f.Eberhard',University='Groß-Gerau',Gender='>',Birthdate
='1912-11-17'
WHERE Year='1945' AND Name='Eberhard' AND Year='e.1945' AND Name=
'f.Eberhard' AND University='Groß-Gerau' AND Gender='>' AND Birthdate=
'1912-11-17';
UPDATE table_not_specified SET Year='1995',Name='Fritz',Year='e.1995',
Name='f.Fritz',University='Waldshut',Gender='<',Birthdate='1907-08-08'
WHERE Year='1995' AND Name='Fritz' AND Year='e.1995' AND Name='f.Fritz'
 AND University='Waldshut' AND Gender='<' AND Birthdate='1907-08-08';
UPDATE table_not_specified SET Year='1999',Name='Maria',Year='e.1999',
Name='f.Maria',University='Hermsdorf',Gender='#',Birthdate='1914-09-17'
WHERE Year='1999' AND Name='Maria' AND Year='e.1999' AND Name='f.Maria'
 AND University='Hermsdorf' AND Gender='#' AND Birthdate='1914-09-17';
UPDATE table_not_specified SET Year='1983',Name='Ilse',Year='e.1983',
Name='f.Ilse',University='Lübars',Gender='$',Birthdate='1909-02-09'
WHERE Year='1983' AND Name='Ilse' AND Year='e.1983' AND Name='f.Ilse'
 AND University='Lübars' AND Gender='$' AND Birthdate='1909-02-09';
UPDATE table_not_specified SET Year='1985',Name='Dorothea',Year=
'e.1985',Name='f.Dorothea',University='Lübars',Gender='$',Birthdate=
'1910-02-07'
WHERE Year='1985' AND Name='Dorothea' AND Year='e.1985' AND Name=
'f.Dorothea' AND University='Lübars' AND Gender='$' AND Birthdate=
'1910-02-07';
UPDATE table_not_specified SET Year='1984',Name='Lucie',Year='e.1984',
Name='f.Lucie',University='Lübars',Gender='''',Birthdate='1887-07-09'
WHERE Year='1984' AND Name='Lucie' AND Year='e.1984' AND Name='f.Lucie'
 AND University='Lübars' AND Gender='''' AND Birthdate='1887-07-09';
-- 8 persons
COMMIT;
-- Output on yyyy-mm-dd hh:mm:ss by Dbat script ../web/spec/test/selec02.xml, Excel, more
--
