java -cp ../dist/dbat.jar org.teherba.dbat.Dbat -c ../etc/worddb.properties -e UTF-8 -m update -t tartable -4 "select * from c01"
-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
UPDATE tartable SET name='Martha',univ='Freiburg',year=1999,gender='&',
birth='1909-11-17'
WHERE name='Martha' AND univ='Freiburg' AND year=1999 AND gender='&'
 AND birth='1909-11-17';
UPDATE tartable SET name='Johannes',univ='Schramberg',year=1992,gender=
'<',birth='1911-06-03'
WHERE name='Johannes' AND univ='Schramberg' AND year=1992 AND gender=
'<' AND birth='1911-06-03';
UPDATE tartable SET name='Eberhard',univ='Groß-Gerau',year=1945,gender=
'>',birth='1912-11-17'
WHERE name='Eberhard' AND univ='Groß-Gerau' AND year=1945 AND gender=
'>' AND birth='1912-11-17';
UPDATE tartable SET name='Fritz',univ='Waldshut',year=1995,gender='<',
birth='1907-08-08'
WHERE name='Fritz' AND univ='Waldshut' AND year=1995 AND gender='<'
 AND birth='1907-08-08';
COMMIT;
