wget -q -O - "http://localhost:8080/dbat/servlet?spec=test/xslt_brackets&mode=jdbc"
-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Martha','Freiburg',1999,'&',{d'1909-11-17'});
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Eberhard','Groß-Gerau',1945,'>',{d'1912-11-17'});
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Fritz','Waldshut',1995,'<',{d'1907-08-08'});
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Maria','Hermsdorf',1999,'#',{d'1914-09-17'});
INSERT INTO c01 (name,univ,year,gender,birth)
VALUES ('Dorothea','Lübars',1985,'$',{d'1910-02-07'});
-- 5 Persons
COMMIT;
-- Output on yyyy-mm-dd hh:mm:ss by Dbat script test/xslt_brackets, Excel, more
--
