Dorothea                                Fischer                                 F1910-02-07Berlin                                         1985
Eberhard                                Fischer                                 M1912-11-17Gro�-Gerau                                     1945
Fritz                                   Fischer                                 M1907-08-08Waldshut                                       1995
Ilse                                    Ritter                                  F1909-02-09L�bars                                         1983
Johannes                                Fischer                                 M1911-06-03Schramberg                                     1992
Lucie                                   Ritter                                  F1887-07-09L�bars                                         1984
Maria                                   Ritter                                  F1914-09-17Berlin-Hermsdorf                               1999
Martha                                  Fischer                                 F1909-11-17Freiburg                                       1999
Teherba                                 Ritter                                  F1886-02-04Oranienburg                                    1968
