-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
INSERT INTO table_not_specified (name,family,gender,birth,place,decease
)
VALUES ('Dorothea','Fischer','F','1910-02-07','Berlin',1985);
INSERT INTO table_not_specified (name,family,gender,birth,place,decease
)
VALUES ('Eberhard','Fischer','M','1912-11-17','Gro�-Gerau',1945);
INSERT INTO table_not_specified (name,family,gender,birth,place,decease
)
VALUES ('Fritz','Fischer','M','1907-08-08','Waldshut',1995);
INSERT INTO table_not_specified (name,family,gender,birth,place,decease
)
VALUES ('Ilse','Ritter','F','1909-02-09','L�bars',1983);
INSERT INTO table_not_specified (name,family,gender,birth,place,decease
)
VALUES ('Johannes','Fischer','M','1911-06-03','Schramberg',1992);
INSERT INTO table_not_specified (name,family,gender,birth,place,decease
)
VALUES ('Lucie','Ritter','F','1887-07-09','L�bars',1984);
INSERT INTO table_not_specified (name,family,gender,birth,place,decease
)
VALUES ('Maria','Ritter','F','1914-09-17','Berlin-Hermsdorf',1999);
INSERT INTO table_not_specified (name,family,gender,birth,place,decease
)
VALUES ('Martha','Fischer','F','1909-11-17','Freiburg',1999);
INSERT INTO table_not_specified (name,family,gender,birth,place,decease
)
VALUES ('Teherba','Ritter','F','1886-02-04','Oranienburg',1968);
-- 9 Persons
COMMIT;
-- 9 ;
-- Output on yyyy-mm-dd hh:mm:ss by Dbat script test/crud03, Excel, more
--
