-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
UPDATE table_not_specified SET name='Dorothea',family='Fischer',gender=
'F',birth='1910-02-07',place='Berlin',decease=1985
WHERE name='Dorothea' AND family='Fischer' AND gender='F' AND birth=
'1910-02-07' AND place='Berlin' AND decease=1985;
UPDATE table_not_specified SET name='Eberhard',family='Fischer',gender=
'M',birth='1912-11-17',place='Gro�-Gerau',decease=1945
WHERE name='Eberhard' AND family='Fischer' AND gender='M' AND birth=
'1912-11-17' AND place='Gro�-Gerau' AND decease=1945;
UPDATE table_not_specified SET name='Fritz',family='Fischer',gender='M'
,birth='1907-08-08',place='Waldshut',decease=1995
WHERE name='Fritz' AND family='Fischer' AND gender='M' AND birth=
'1907-08-08' AND place='Waldshut' AND decease=1995;
UPDATE table_not_specified SET name='Ilse',family='Ritter',gender='F',
birth='1909-02-09',place='L�bars',decease=1983
WHERE name='Ilse' AND family='Ritter' AND gender='F' AND birth=
'1909-02-09' AND place='L�bars' AND decease=1983;
UPDATE table_not_specified SET name='Johannes',family='Fischer',gender=
'M',birth='1911-06-03',place='Schramberg',decease=1992
WHERE name='Johannes' AND family='Fischer' AND gender='M' AND birth=
'1911-06-03' AND place='Schramberg' AND decease=1992;
UPDATE table_not_specified SET name='Lucie',family='Ritter',gender='F',
birth='1887-07-09',place='L�bars',decease=1984
WHERE name='Lucie' AND family='Ritter' AND gender='F' AND birth=
'1887-07-09' AND place='L�bars' AND decease=1984;
UPDATE table_not_specified SET name='Maria',family='Ritter',gender='F',
birth='1914-09-17',place='Berlin-Hermsdorf',decease=1999
WHERE name='Maria' AND family='Ritter' AND gender='F' AND birth=
'1914-09-17' AND place='Berlin-Hermsdorf' AND decease=1999;
UPDATE table_not_specified SET name='Martha',family='Fischer',gender=
'F',birth='1909-11-17',place='Freiburg',decease=1999
WHERE name='Martha' AND family='Fischer' AND gender='F' AND birth=
'1909-11-17' AND place='Freiburg' AND decease=1999;
UPDATE table_not_specified SET name='Teherba',family='Ritter',gender=
'F',birth='1886-02-04',place='Oranienburg',decease=1968
WHERE name='Teherba' AND family='Ritter' AND gender='F' AND birth=
'1886-02-04' AND place='Oranienburg' AND decease=1968;
-- 9 Persons
COMMIT;
-- 9 ;
-- Output on yyyy-mm-dd hh:mm:ss by Dbat script test/crud03, Excel, more
--
