-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
INSERT INTO table_not_specified (loc,gender,birth)
VALUES ('Lübars','$','1909-02-09');
INSERT INTO table_not_specified (loc,gender,birth)
VALUES ('Lübars','$','1910-02-07');
INSERT INTO table_not_specified (loc,gender,birth)
VALUES ('Lübars','''','1887-07-09');
COMMIT;
-- 3 ;
-- Output on yyyy-mm-dd hh:mm:ss by Dbat script test/visible05, Excel, more
--
