-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
UPDATE table1 SET loc='Lübars',gender='$',birth='1909-02-09'
WHERE loc='Lübars' AND gender='$' AND birth='1909-02-09';
UPDATE table1 SET loc='Lübars',gender='$',birth='1910-02-07'
WHERE loc='Lübars' AND gender='$' AND birth='1910-02-07';
UPDATE table1 SET loc='Lübars',gender='''',birth='1887-07-09'
WHERE loc='Lübars' AND gender='''' AND birth='1887-07-09';
COMMIT;
-- 3 ;
-- Output on yyyy-mm-dd hh:mm:ss by Dbat script test/visible05, Excel, more
--
