-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
UPDATE table_not_specified SET University='Lübars',Gender='$',Birthdate
='1909-02-09'
WHERE University='Lübars' AND Gender='$' AND Birthdate='1909-02-09';
UPDATE table_not_specified SET University='Lübars',Gender='$',Birthdate
='1910-02-07'
WHERE University='Lübars' AND Gender='$' AND Birthdate='1910-02-07';
UPDATE table_not_specified SET University='Lübars',Gender='''',
Birthdate='1887-07-09'
WHERE University='Lübars' AND Gender='''' AND Birthdate='1887-07-09';
COMMIT;
-- 3 ;
-- Output on yyyy-mm-dd hh:mm:ss by Dbat script test/visible05, Excel, more
--
