java -cp ../dist/dbat.jar org.teherba.dbat.Dbat -c ../etc/worddb.properties -e UTF-8 -d vw1
-- SQL generated by Dbat at 2012-06-01T22:56:50
-- MySQL 5.1.62-0ubuntu0.11.10.1 with MySQL-AB JDBC Driver mysql-connector-java-5.1.11 ( Revision: ${svn.Revision} )
DROP   VIEW vw1;
CREATE VIEW vw1
	( name	VARCHAR(16) NOT NULL -- Name of the Relative
	, birth	DATE
	);
COMMIT;
-- finished at 2012-06-01T22:56:51
