-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
DROP   PROCEDURE x07 $
CREATE PROCEDURE x07
	( IN	iname0	VARCHAR(16)
	, OUT	odec1	DECIMAL(12)
	, OUT	odec2	DECIMAL(18,3)
	, OUT	odate3	DATE
	, OUT	otime4	TIME
	, OUT	ots5	TIMESTAMP
	)
	BEGIN
	END;
	$
