-- generated by etc/xslt/gen_spec_index.xsl at 2016-07-16 09:47:09

INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'','describe','en','DDL of a Table/View',
	'Shows the DDL Description of a Table or View '
	,'&table=spec_ind ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','alt_bedingt','en','alt_name',
	''
	,'&kond= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','alt_name','en','alt_name',
	''
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','ikas_select','en','ikas_select',
	''
	,'&kond= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','ilas_select','en','ilas_select',
	''
	,'&kond=0');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','ilas_update','en','ilas_select',
	''
	,'&kond= &termin= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','index','en','index',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','iueb1c_select','en','sepa1c_select',
	''
	,'&kond= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','liste_bedingt','en','liste_bedingt',
	''
	,'&kond=TRUE ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','liste_blz','en','liste_blz',
	''
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','liste_folgetermine','en','liste_folgetermine',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','liste_name','en','liste_name',
	''
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','liste_nummer','en','liste_nummer',
	''
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','mitglieder','en','drk/mitglieder',
	''
	,'&Anrede= &BIC= &BLZ= &Beitrag= &Bemerkung= &Eintritt= &Email= &Folgetermin= &GebDatum= &IBAN= &Konto= &Nachname= &Nummer= &PLZ= &Quittung= &Strasse= &Teilbetrag= &Teilzahl= &Telefon= &Titel= &Vorname= &Wohnort= &remote_user= &search_Nachname= &search_Vorname= &update_count= &user= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','sepa1c_select','en','sepa1c_select',
	''
	,'&kond= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','sepa_select','en','sepa_select',
	''
	,'&kond= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','teilbetrag_falsch','en','teilbetrag_falsch',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','teilbetrag_select','en','teilbetrag_select',
	''
	,'&Nachname= &Vorname= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','haushaltsposition','en','haushaltsposition',
	''
	,'&hhnr= &hhpos=verw ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','haushaltspositionen','en','haushaltspositionen',
	''
	,'&jahr=2015 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','index','en','index',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','journal','en','fibu/journal',
	''
	,'&agiban= &betrag= &buchtag= &fibukto= &partner= &remote_user= &search_agiban= &search_betrag= &search_buchtag= &search_partner= &update_count= &vwz= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','konten','en','konten',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','kontenblaetter','en','kontenblaetter',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','kontenblatt','en','kontenblatt',
	''
	,'&beschreibung= &fibukto=1900 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','kontenblatts','en','kontenblatt',
	''
	,'&beschreibung= &fibukto=1900 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','sachkonten','en','sachkonten',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','salden','en','salden',
	''
	,'&fibukto=90__ ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'','index','en','index',
	''
	,'&lang=en ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'maint','spec_outline','en','spec_outline',
	'Overview of the Specifications with Links and Parameters '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','bamfadressen','en','BAMF-Adressen 79341 Kenzingen',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','bamfliste','en','BAMF-Liste 79341 Kenzingen',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','betreuer','en','betreuer',
	''
	,'&nachname= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','ehepaare','en','ehepaare',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','emailadressen','en','emailadressen',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','gruppe','en','gruppe',
	''
	,'&gruppe=Bejzaku ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','gruppen','en','gruppen',
	''
	,'&strasse=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','index','en','index',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','kinder','en','kinder',
	''
	,'&art= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','land_status','en','land_status',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','patenliste','en','patenliste',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','patenverein','en','patenverein',
	'Series letter (file tayloring) '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','schule','en','schule',
	''
	,'&kurs= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','standort','en','standort',
	''
	,'&standort=Balgerstr. 30 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','aggr01','en','aggr01',
	'Column Aggregation with linked values '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','ajax01','en','ajax01',
	'First Ajax Test '
	,'&changed= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','ajax02','en','ajax02',
	'Data to be retrieved by specification ajax01.xml '
	,'&name=Dorothea ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','align01','en','align01',
	'Select from test table with explicit widths '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','align02','en','align02',
	'Select from test table with right aligned numbers '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','callproc','en','callproc',
	'Activation of a Stored Procedure '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','callx10','en','callx10',
	'Activation of a Stored Procedure; results into parameters '
	,'&iname0= &odate3= &odec1= &odec2= &otime4= &ots5= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','choose06','en','choose06',
	'Test of Conditional Compilation with "choose" '
	,'&switch=yes ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','choose07','en','choose07',
	'Test of Conditional Compilation with Regular Expressions '
	,'&par=x ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color04','en','color04',
	'Select from test table - with colors and linked values '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color05','en','color05',
	'Select from test table - with colors and linked values '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color07','en','color07',
	'Select from test table with "sorttable.js" '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color08','en','color08',
	'Select from test table - with colors on rows '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color09','en','color09',
	'Colors on columns and rows '
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','column02','en','column02',
	'Select from test table - same as selec02 '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','counter01','en','counter01',
	'Counter Test '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud01','en','test/crud01',
	''
	,'&birth= &decease= &family= &gender= &name= &place= &remote_user= &search_decease= &search_family= &search_name= &update_count= &user= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud02','en','test/crud02',
	''
	,'&birth= &changed= &decease= &family= &gender= &name= &place= &remote_user= &search_family= &search_gender= &search_name= &update_count= &user= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud03','en','test/crud03',
	''
	,'&birth= &decease= &family= &gender= &name= &place= &remote_user= &search_family= &search_gender= &search_name= &update_count= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud04','en','test/crud04',
	''
	,'&birth= &changed= &decease= &family= &gender= &name= &place= &remote_user= &search_decease= &search_family= &search_name= &update_count= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud05','en','test/crud05',
	'Maintain Relatives (with field references) '
	,'&birth= &decease= &family= &gender= &name= &place= &remote_user= &search_decease= &search_family= &search_name= &update_count= &user= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud06','en','test/crud06',
	''
	,'&birth= &decease= &family= &gender= &name= &place= &search_family= &search_gender= &search_name= &update_count= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','enum01','en','enum01',
	'Fetch Enumerations into Parameters '
	,'&code=initcode &code_count= &display=initdisplay ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','enum02','en','enum02',
	'Fetch Enumerations and build dynamic listbox '
	,'&gender=N ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','fragment01','en','fragment01',
	'Select with fragment in link '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','grouping','en','grouping',
	'Test multiple header lines for control exchanges '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','highlight','en','highlight',
	'Column with Highlighting of a Keyword '
	,'&keyword=er ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','image01','en','image01',
	'Select from a Table with Images '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','image02','en','image01',
	'Select from a Table with Pagebreaks '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','includer','en','includer',
	'tests the inclusion of system entities '
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','index','en','Test Specifications',
	'List of the Specifications for Dbat Test Cases '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','listbox','en','listbox',
	'List Box and List Parameter Test '
	,'&birthchar= &birthint= &namebox= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','listbox2','en','listbox',
	'List Box and List Parameter Test '
	,'&birthchar= &birthint= &namebox= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','minimal','en','',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','minusconn','en','minusconn',
	'Spec without Connection Id '
	,'&conn= &tabname=c01 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','multicss','en','multijs',
	'Test with 2 Stylesheets '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','multijs','en','multijs',
	'Test with 2 Javascripts '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','order01','en','order01',
	'Select from test table with ORDER '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','order02','en','order02',
	'Select from test table with ORDER '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','parmform','en','parmform',
	'Test of the format="..." attribute in &lt;parm&gt; '
	,'&VALUE= &value= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','parmlink','en','parmlink',
	'Test of an HTML Link with Parameter Substitution '
	,'&name=M &year=1995 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','pivot03','en','pivot03',
	'Pivot matrix output with linked values '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','pivot04','en','pivot04',
	'Pivot matrix output with linked values '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','rewrite','en','rewrite',
	'Rewriting of Parameters '
	,'&DBSYS= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec01','en','selec01',
	'Select from test table '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec02','en','selec02',
	'Select from test table - with linked values '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec03','en','selec03',
	'Two SELECTs from test table '
	,'&birth= &name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec04','en','selec04',
	'Select from a CLOB table '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec05','en','selec05',
	'Select from test table - with <read> element '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selecde1','en','selecde1',
	'Select with date, decimal, and timestamp '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selnull','en','selnull',
	'Select with NULL values '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','stylesheet1','en','stylesheet1',
	'Explicit Stylesheet "/dbat/spec/stylesheet.css" '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','switchconn','en','switchconn',
	'Switch to another database connection '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','taylor5','en','taylor5',
	'Select from test table and replace variables in pattern file (file tayloring) '
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','textarea','en','textarea',
	'Test of an input text area '
	,'&WORDLIST= &wordlist= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail01','en','trail01',
	'No Trailer '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail02','en','trail02',
	'Trailer with "out dbat" '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail03','en','trail03',
	'Trailer with "out dbat script" '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail04','en','trail04',
	'Trailer with "out dbat script xls" '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail05','en','trail05',
	'Trailer with "out dbat script xls more" '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail06','en','trail06',
	'Trailer with "out dbat more" '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','uml01','en','test/uml01',
	'Test of URL encoding with accented letters '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','var01','en','test/var01',
	'Test of the var element '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','var02','en','test/var02',
	'Test of the var element with data types '
	,'&birth=1800-01-01 &changed=1900-01-01 00:00:00 &decease=1800 &name=A ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','var03','en','test/var03',
	'Test of the var element with data types '
	,'&birth=1800-01-01 &changed=1900-01-01 00:00:00 &decease=1800 &name=A ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','visible05','en','visible05',
	'Select from test table - suppress subsequent column values in groups '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','with_cte','en','with_cte',
	'test the SQL &lt;with&gt; Syntax for Common Table Expressions '
	,'&prefix=backe ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','xslt_brackets','en','xslt_brackets',
	'Select from test table with XSLT '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'','describe','de','DDL of a Table/View',
	'Gibt die DDL-Beschreibung einer Tabelle oder View aus '
	,'&table=spec_ind ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','alt_bedingt','de','alt_name',
	'Lastschriften 2013 '
	,'&kond= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','alt_name','de','alt_name',
	'Lastschriften 2013 '
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','ikas_select','de','ikas_select',
	'Parameter für Inlandslastschriften (kurz) selektieren '
	,'&kond= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','ilas_select','de','ilas_select',
	'Parameter für Inlandslastschriften selektieren '
	,'&kond=0');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','ilas_update','de','ilas_select',
	'Lastschrifttermine fortschreiben '
	,'&kond= &termin= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','index','de','index',
	'Alle DRK-Abfragen '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','iueb1c_select','de','sepa1c_select',
	'Parameter für 1-Cent-SEPA-ßberweisungen selektieren '
	,'&kond= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','liste_bedingt','de','liste_bedingt',
	'Mitgliederliste (mit Bedingung) '
	,'&kond=TRUE ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','liste_blz','de','liste_blz',
	'Mitgliederliste (nach Namen sortiert) '
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','liste_folgetermine','de','liste_folgetermine',
	'Mitgliederliste (mit Bedingung) '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','liste_name','de','liste_name',
	'Mitgliederliste (nach Namen sortiert) '
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','liste_nummer','de','liste_nummer',
	'Mitgliederliste (nach Namen sortiert) '
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','mitglieder','de','drk/mitglieder',
	''
	,'&Anrede= &BIC= &BLZ= &Beitrag= &Bemerkung= &Eintritt= &Email= &Folgetermin= &GebDatum= &IBAN= &Konto= &Nachname= &Nummer= &PLZ= &Quittung= &Strasse= &Teilbetrag= &Teilzahl= &Telefon= &Titel= &Vorname= &Wohnort= &remote_user= &search_Nachname= &search_Vorname= &update_count= &user= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','sepa1c_select','de','sepa1c_select',
	'Parameter für 1-Cent-SEPA-ßberweisungen selektieren '
	,'&kond= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','sepa_select','de','sepa_select',
	'Parameter für SEPA-Lastschriften selektieren '
	,'&kond= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','teilbetrag_falsch','de','teilbetrag_falsch',
	'Teilbetragsprüfung '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'drk','teilbetrag_select','de','teilbetrag_select',
	'Teilbetragsprüfung '
	,'&Nachname= &Vorname= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','haushaltsposition','de','haushaltsposition',
	'Haushaltsposition '
	,'&hhnr= &hhpos=verw ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','haushaltspositionen','de','haushaltspositionen',
	'alle Haushaltspositionen '
	,'&jahr=2015 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','index','de','index',
	'Finanzbuchhaltungsabfragen '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','journal','de','fibu/journal',
	''
	,'&agiban= &betrag= &buchtag= &fibukto= &partner= &remote_user= &search_agiban= &search_betrag= &search_buchtag= &search_partner= &update_count= &vwz= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','konten','de','konten',
	'Liste der Fibu-Konten und Salden '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','kontenblaetter','de','kontenblaetter',
	'Druckliste der Fibu-Konten-Blätter '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','kontenblatt','de','kontenblatt',
	'Kontoblatt mit allen Buchungen '
	,'&beschreibung= &fibukto=1900 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','kontenblatts','de','kontenblatt',
	'Kontoblatt mit allen Buchungen '
	,'&beschreibung= &fibukto=1900 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','sachkonten','de','sachkonten',
	'alle Sachkonten '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'fibu','salden','de','salden',
	'Konten 90xx mit allen Buchungen '
	,'&fibukto=90__ ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'','index','de','index',
	''
	,'&lang=en ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'maint','spec_outline','de','spec_outline',
	'Übersicht über die Spezifikationen mit Links und Parametern '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','bamfadressen','de','BAMF-Adressen 79341 Kenzingen',
	'BAMF-Adressen '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','bamfliste','de','BAMF-Liste 79341 Kenzingen',
	'BAMF-Liste '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','betreuer','de','betreuer',
	'Betreuer-Daten '
	,'&nachname= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','ehepaare','de','ehepaare',
	'Liste der Flüchtlingsehepaare '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','emailadressen','de','emailadressen',
	'EMail-Adressen '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','gruppe','de','gruppe',
	'eine Gruppe mit Mitgliedern '
	,'&gruppe=Bejzaku ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','gruppen','de','gruppen',
	'Liste aller Gruppen '
	,'&strasse=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','index','de','index',
	'Liste aller Migrationsabfragen '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','kinder','de','kinder',
	'Liste der Flüchtlinge (nach Alter sortiert) '
	,'&art= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','land_status','de','land_status',
	'Status und Herkunftsländer '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','patenliste','de','patenliste',
	'Liste der Patenvereinbarungen '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','patenverein','de','patenverein',
	'Serienbrief: Patenvereinbarungen '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','schule','de','schule',
	'Schulen / Kurse / Kindergärten '
	,'&kurs= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'migr','standort','de','standort',
	'ein Standort mit allen Gruppen '
	,'&standort=Balgerstr. 30 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','aggr01','de','aggr01',
	'Aggregierte Spalte mit Verweisen auf den Werten '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','ajax01','de','ajax01',
	'Erster Ajax-Test '
	,'&changed= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','ajax02','de','ajax02',
	'Daten für Spezifikation ajax01.xml '
	,'&name=Dorothea ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','align01','de','align01',
	'Abfrage der Test-Tabelle mit festen Zellenbreiten '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','align02','de','align02',
	'Abfrage der Test-Tabelle mit rechtsbündigen Zahlen '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','callproc','de','callproc',
	'Aufruf einer Stored Procedure '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','callx10','de','callx10',
	'Aufruf einer Stored Procedure; Ergebnis im Parametersatz '
	,'&iname0= &odate3= &odec1= &odec2= &otime4= &ots5= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','choose06','de','choose06',
	'Test der bedingten Compilierung mit "choose" '
	,'&switch=yes ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','choose07','de','choose07',
	'Test der bedingten Compilierung mit Regulären Ausdrücken '
	,'&par=x ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color04','de','color04',
	'Abfrage der Test-Tabelle mit farbigem Hintergrund und Verweisen auf den Werten '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color05','de','color05',
	'Abfrage der Test-Tabelle mit farbigem Hintergrund und Verweisen auf den Werten '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color07','de','color07',
	'Abfrage der Test-Tabelle mit sortierbaren Spalten '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color08','de','color08',
	'Abfrage der Test-Tabelle mit farbigen Zeilen '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color09','de','color09',
	'Farben auf Spalten und Zeilen '
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','column02','de','column02',
	'Abfrage der Test-Tabelle - wie selec02 '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','counter01','de','counter01',
	'Test des Zeilenzählers '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud01','de','test/crud01',
	''
	,'&birth= &decease= &family= &gender= &name= &place= &remote_user= &search_decease= &search_family= &search_name= &update_count= &user= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud02','de','test/crud02',
	''
	,'&birth= &changed= &decease= &family= &gender= &name= &place= &remote_user= &search_family= &search_gender= &search_name= &update_count= &user= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud03','de','test/crud03',
	''
	,'&birth= &decease= &family= &gender= &name= &place= &remote_user= &search_family= &search_gender= &search_name= &update_count= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud04','de','test/crud04',
	''
	,'&birth= &changed= &decease= &family= &gender= &name= &place= &remote_user= &search_decease= &search_family= &search_name= &update_count= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud05','de','test/crud05',
	''
	,'&birth= &decease= &family= &gender= &name= &place= &remote_user= &search_decease= &search_family= &search_name= &update_count= &user= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud06','de','test/crud06',
	''
	,'&birth= &decease= &family= &gender= &name= &place= &search_family= &search_gender= &search_name= &update_count= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','enum01','de','enum01',
	'Parameter aus einer Enumeration füllen '
	,'&code=initcode &code_count= &display=initdisplay ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','enum02','de','enum02',
	'Dyn. Listbox mit Parametern einer Enumeration füllen '
	,'&gender=N ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','fragment01','de','fragment01',
	'Abfrage mit Fragment im Link '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','grouping','de','grouping',
	'Test der wiederholten Überschriften beim Gruppenwechsel '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','highlight','de','highlight',
	'Spalte mit Hervorhebung eines Teilworts '
	,'&keyword=er ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','image01','de','image01',
	'Abfrage einer Tabelle mit Bildern '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','image02','de','image01',
	'Abfrage einer Tabelle mit Seitenwechseln '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','includer','de','includer',
	'testet die Einbindung von System Entities '
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','index','de','Test Specifications',
	'Liste der Spezifikationen für die Dbat-Testfälle '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','listbox','de','listbox',
	'Test von Auswahl- und Parameterlisten '
	,'&birthchar= &birthint= &namebox= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','listbox2','de','listbox',
	'Test von Auswahl- und Parameterlisten '
	,'&birthchar= &birthint= &namebox= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','minimal','de','',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','minusconn','de','minusconn',
	''
	,'&conn= &tabname=c01 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','multicss','de','multijs',
	'Test mit 2 Stylesheets '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','multijs','de','multijs',
	'Test mit 2 Javascripts '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','order01','de','order01',
	'Suche in der Test-Tabelle mit ORDER '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','order02','de','order02',
	'Abfrage der Test-Tabelle mit ORDER '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','parmform','de','parmform',
	'Test des format-Attributs in in &lt;parm&gt; '
	,'&VALUE= &value= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','parmlink','de','parmlink',
	'Test eines HTML-Links mit Parameter-Ersetzung '
	,'&name=M &year=1995 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','pivot03','de','pivot03',
	'Ausgabe einer Pivot-Matrix mit Verweisen auf den Werten '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','pivot04','de','pivot04',
	'Ausgabe einer Pivot-Matrix mit Verweisen auf den Werten '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','rewrite','de','rewrite',
	'Parameter umschreiben '
	,'&DBSYS= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec01','de','selec01',
	'Abfrage der Test-Tabelle '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec02','de','selec02',
	'Abfrage der Test-Tabelle mit Verweisen auf den Werten '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec03','de','selec03',
	'Zwei Abfragen der Test-Tabelle '
	,'&birth= &name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec04','de','selec04',
	'Abfrage einer CLOB-Tabelle '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec05','de','selec05',
	'Abfrage der Test-Tabelle mit <read>-Element '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selecde1','de','selecde1',
	'Abfrage mit Date, Decimal und Timestamp '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selnull','de','selnull',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','stylesheet1','de','stylesheet1',
	'Explizite Stylesheet-Angabe "/dbat/spec/stylesheet.css" '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','switchconn','de','switchconn',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','taylor5','de','taylor5',
	'Serienbrieffunktion mit Variablenersetzung '
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','textarea','de','textarea',
	'Test eines Eingabe-Textbereichs '
	,'&WORDLIST= &wordlist= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail01','de','trail01',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail02','de','trail02',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail03','de','trail03',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail04','de','trail04',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail05','de','trail05',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail06','de','trail06',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','uml01','de','test/uml01',
	'Test der URL-Codierung von Umlauten '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','var01','de','test/var01',
	'Test des var-Elements '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','var02','de','test/var02',
	'Test des var-Elements mit Datentypen '
	,'&birth=1800-01-01 &changed=1900-01-01 00:00:00 &decease=1800 &name=A ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','var03','de','test/var03',
	'Test des var-Elements mit Datentypen '
	,'&birth=1800-01-01 &changed=1900-01-01 00:00:00 &decease=1800 &name=A ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','visible05','de','visible05',
	'Abfrage der Test-Tabelle mit Unterdrückung von Werten in einer Gruppe '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','with_cte','de','with_cte',
	'testet die SQL-Syntax von &lt;with&gt; für "Common Table Expressions" '
	,'&prefix=backe ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','xslt_brackets','de','xslt_brackets',
	'Abfrage der Test-Tabelle mit XSLT '
	,'&name=%r ');
COMMIT;