-- generated by etc/xslt/gen_spec_index.xsl at 2016-04-16 14:05:04

INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'','describe','de','DDL of a Table/View',
	'Gibt die DDL-Beschreibung einer Tabelle oder View aus '
	,'&table=spec_ind ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'','index','de','Specifications',
	'in allen Teilbereichen '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'maint','spec_outline','de','spec_outline',
	'Übersicht über die Spezifikationen mit Links und Parametern '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','aggr01','de','aggr01',
	'Aggregierte Spalte mit Verweisen auf den Werten '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','ajax01','de','ajax01',
	'Erster Ajax-Test '
	,'&changed= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','ajax02','de','ajax02',
	'Daten für Spezifikation ajax01.xml '
	,'&name=Dorothea ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','align01','de','align01',
	'Abfrage der Test-Tabelle mit festen Zellenbreiten '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','align02','de','align02',
	'Abfrage der Test-Tabelle mit rechtsbündigen Zahlen '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','callproc','de','callproc',
	'Aufruf einer Stored Procedure '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','callx10','de','callx10',
	'Aufruf einer Stored Procedure; Ergebnis im Parametersatz '
	,'&iname0= &odate3= &odec1= &odec2= &otime4= &ots5= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','check_word','de','check_word',
	''
	,'&word= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','choose06','de','choose06',
	'Test der bedingten Compilierung mit "choose" '
	,'&switch=yes ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','choose07','de','choose07',
	'Test der bedingten Compilierung mit Regulären Ausdrücken '
	,'&par=x ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color04','de','color04',
	'Abfrage der Test-Tabelle mit farbigem Hintergrund und Verweisen auf den Werten '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color05','de','color05',
	'Abfrage der Test-Tabelle mit farbigem Hintergrund und Verweisen auf den Werten '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color07','de','color07',
	'Abfrage der Test-Tabelle mit sortierbaren Spalten '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color08','de','color08',
	'Abfrage der Test-Tabelle mit farbigen Zeilen '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color09','de','color09',
	'Farben auf Spalten und Zeilen '
	,'&name= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','column02','de','column02',
	'Abfrage der Test-Tabelle - wie selec02 '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','counter01','de','counter01',
	'Test des Zeilenzählers '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud01','de','test/crud01',
	''
	,'&birth= &decease= &family= &gender= &name= &place= &remote_user= &search_decease= &search_family= &search_name= &update_count= &user= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud02','de','test/crud02',
	''
	,'&birth= &changed= &decease= &family= &gender= &name= &place= &remote_user= &search_family= &search_gender= &search_name= &update_count= &user= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud03','de','test/crud03',
	''
	,'&birth= &decease= &family= &gender= &name= &place= &remote_user= &search_family= &search_gender= &search_name= &update_count= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud04','de','test/crud04',
	''
	,'&birth= &changed= &decease= &family= &gender= &name= &place= &remote_user= &search_decease= &search_family= &search_name= &update_count= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud05','de','test/crud05',
	''
	,'&birth= &decease= &family= &gender= &name= &place= &remote_user= &search_decease= &search_family= &search_name=Georg &update_count= &user= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud06','de','test/crud06',
	''
	,'&birth= &decease= &family= &gender= &name= &place= &search_family= &search_gender= &search_name= &update_count= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','enum01','de','enum01',
	'Parameter aus einer Enumeration füllen '
	,'&code=initcode &display=initdisplay ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','enum02','de','enum02',
	'Dyn. Listbox mit Parametern einer Enumeration füllen '
	,'&gender=N ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','fragment01','de','fragment01',
	'Abfrage mit Fragment im Link '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','grouping','de','grouping',
	'Test der wiederholten Überschriften beim Gruppenwechsel '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','highlight','de','highlight',
	'Liste der Spezifikationen mit Hervorhebung eines Schlagworts '
	,'&keyword=ajax ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','image01','de','image01',
	'Abfrage einer Tabelle mit Bildern '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','image02','de','image01',
	'Abfrage einer Tabelle mit Seitenwechseln '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','index','de','Test Specifications',
	'Liste der Spezifikationen für die Dbat-Testfälle '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','listbox','de','listbox',
	'Test von Auswahl- und Parameterlisten '
	,'&birthchar= &birthint= &namebox= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','listbox2','de','listbox',
	'Test von Auswahl- und Parameterlisten '
	,'&birthchar= &birthint= &namebox= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','minimal','de','',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','minusconn','de','minusconn',
	''
	,'&conn= &tabname=c01 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','multicss','de','multijs',
	'Test mit 2 Stylesheets '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','multijs','de','multijs',
	'Test mit 2 Javascripts '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','nulls','de','test/nulls',
	''
	,'&db2sys= &search_db2sys= &update_count= &weekday= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','order01','de','order01',
	'Suche in der Test-Tabelle mit ORDER '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','order02','de','order02',
	'Abfrage der Test-Tabelle mit ORDER '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','parmform','de','parmform',
	'Test des format-Attributs in in &lt;parm&gt; '
	,'&VALUE= &value= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','parmlink','de','parmlink',
	'Test eines HTML-Links mit Parameter-Ersetzung '
	,'&name=M &year=1995 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','pivot03','de','pivot03',
	'Ausgabe einer Pivot-Matrix mit Verweisen auf den Werten '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','pivot04','de','pivot04',
	'Ausgabe einer Pivot-Matrix mit Verweisen auf den Werten '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','rewrite','de','rewrite',
	'Parameter umschreiben '
	,'&DB2SYS= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec01','de','selec01',
	'Abfrage der Test-Tabelle '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec02','de','selec02',
	'Abfrage der Test-Tabelle mit Verweisen auf den Werten '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec03','de','selec03',
	'Abfrage der Test-Tabelle '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec04','de','selec04',
	'Abfrage einer CLOB-Tabelle '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec05','de','selec05',
	'Abfrage der Test-Tabelle mit <read>-Element '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selnull','de','selnull',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','stylesheet1','de','stylesheet1',
	'Explizite Stylesheet-Angabe "/dbat/spec/stylesheet.css" '
	,'&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','textarea','de','textarea',
	'Test eines Eingabe-Textbereichs '
	,'&WORDLIST= &wordlist= ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail01','de','trail01',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail02','de','trail02',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail03','de','trail03',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail04','de','trail04',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail05','de','trail05',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail06','de','trail06',
	''
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','var01','de','test/var01',
	'Test des var-Elements '
	,'&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','var02','de','test/var02',
	'Test des var-Elements mit Datentypen '
	,'&birth=1800-01-01 &changed=1900-01-01 00:00:00 &decease=1800 &name=A ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','var03','de','test/var03',
	'Test des var-Elements mit Datentypen '
	,'&birth=1800-01-01 &changed=1900-01-01 00:00:00 &decease=1800 &name=A ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','visible05','de','visible05',
	'Abfrage der Test-Tabelle mit Unterdrückung von Werten in einer Gruppe '
	,'');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','with_cte','de','with_cte',
	'testet die SQL-Syntax von &lt;with&gt; für "Common Table Expressions" '
	,'&prefix=backe ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','xslt_brackets','de','xslt_brackets',
	'Abfrage der Test-Tabelle mit XSLT '
	,'&name=%r ');
COMMIT;--
commit;
