-- generated by etc/xslt/gen_spec_index.xsl at 2014-11-11 21:19:12

INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'','describe','en','DDL of a Table/View',
	'Shows the DDL Description of a Table or View ','&table=spec_ind ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'','index','en','Specifications',
	'in all areas ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'maint','spec_outline','en','spec_outline',
	'Overview of the Specifications with Links and Parameters ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','aggr01','en','aggr01',
	'Column Aggregation with linked values ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','ajax01','en','ajax01',
	'First Ajax Test ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','ajax02','en','ajax02',
	'Data to be retrieved by specification ajax01.xml ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','align01','en','align01',
	'Select from test table with explicit widths ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','align02','en','align02',
	'Select from test table with right aligned numbers ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','callproc','en','callproc',
	'Activation of a Stored Procedure ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','callx10','en','callx10',
	'Activation of a Stored Procedure; results into parameters ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','check_word','en','check_word',
	'Test of AJAX functionality ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','choose06','en','choose06',
	'Test of Conditional Compilation with "choose" ','&switch=yes ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','choose07','en','choose07',
	'Test of Conditional Compilation with Regular Expressions ','&par=x ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color04','en','color04',
	'Select from test table - with colors and linked values ','&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color05','en','color05',
	'Select from test table - with colors and linked values ','&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color07','en','color07',
	'Select from test table with "sorttable.js" ','&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color08','en','color08',
	'Select from test table - with colors on rows ','&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','color09','en','color09',
	'Colors on columns and rows ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','column02','en','column02',
	'Select from test table - same as selec02 ','&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','counter01','en','counter01',
	'Counter Test ','&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud01','en','test/crud01',
	'','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud02','en','test/crud02',
	'','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud03','en','test/crud03',
	'','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud04','en','test/crud04',
	'','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud05','en','test/crud05',
	'Maintain Relatives (with field references) ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','crud06','en','test/crud06',
	'','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','enum01','en','enum01',
	'Fetch Enumerations into Parameters ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','enum02','en','enum02',
	'Fetch Enumerations and build dynamic listbox ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','fragment01','en','fragment01',
	'Select with fragment in link ','&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','grouping','en','grouping',
	'Test multiple header lines for control exchanges ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','image01','en','image01',
	'Select from a Table with Images ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','index','en','Test Specifications',
	'List of the Specifications for Dbat Test Cases ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','listbox2','en','listbox',
	'List Box and List Parameter Test ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','listbox','en','listbox',
	'List Box and List Parameter Test ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','minimal','en','',
	'','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','minusconn','en','minusconn',
	'Spec without Connection Id ','&tabname=c01 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','multicss','en','multijs',
	'Test with 2 StylesheetsStylesheets ','&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','multijs','en','multijs',
	'Test with 2 Javascripts ','&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','nulls','en','test/nulls',
	'','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','order01','en','order01',
	'Select from test table with ORDER ','&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','order02','en','order02',
	'Select from test table with ORDER ','&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','parmform','en','parmform',
	'Test of the format="..." attribute in &lt;parm&gt; ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','parmlink','en','parmlink',
	'Test of an HTML Link with Parameter Substitution ','&name=M &year=1995 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','pivot03','en','pivot03',
	'Pivot matrix output with linked values ','&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','pivot04','en','pivot04',
	'Pivot matrix output with linked values ','&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','rewrite','en','rewrite',
	'Rewriting of Parameters ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec01','en','selec01',
	'Select from test table ','&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec02','en','selec02',
	'Select from test table - with linked values ','&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec03','en','selec03',
	'Select from test table ','&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec04','en','selec04',
	'Select from a CLOB table ','&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selec05','en','selec05',
	'Select from test table - with <read> element ','&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','selnull','en','selnull',
	'Select with NULL values ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','stylesheet1','en','stylesheet1',
	'Explicit Stylesheet "/dbat/spec/stylesheet.css" ','&name=%r ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','textarea','en','textarea',
	'Test of an input text area ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail01','en','trail01',
	'No Trailer ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail02','en','trail02',
	'Trailer with "out dbat" ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail03','en','trail03',
	'Trailer with "out dbat script" ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail04','en','trail04',
	'Trailer with "out dbat script xls" ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail05','en','trail05',
	'Trailer with "out dbat script xls more" ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','trail06','en','trail06',
	'Trailer with "out dbat more" ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','var01','en','test/var01',
	'Test of the var element ','&name=% ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','var02','en','test/var02',
	'Test of the var element with data types ','&name=A &birth=1800-01-01 &decease=1800 &changed=1900-01-01 00:00:00 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','var03','en','test/var03',
	'Test of the var element with data types ','&name=A &birth=1800-01-01 &decease=1800 &changed=1900-01-01 00:00:00 ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','visible05','en','visible05',
	'Select from test table - suppress subsequent column values in groups ','');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','with_cte','en','with_cte',
	'test the SQL &lt;with&gt; Syntax for Common Table Expressions ','&prefix=backe ');
COMMIT;
INSERT INTO spec_index (subdir, name, lang, title, comment, params) VALUES (
	'test','xslt_brackets','en','xslt_brackets',
	'Select from test table with XSLT ','&name=%r ');
COMMIT;--
commit;
