#!/usr/bin/perl

# Build a file build.number with a major version, git's commit hash and the current date
# @(#) $Id$
# 2022-02-04, Georg Fischer: 12
#
# Usage: (in ant task "prepare")
#   perl etc/util/update_version.pl > build.number
# The variable $major_version must be manually incremented here.
#------------------------------------------------------------------
#
use strict;
use warnings;
use integer;

    my $major_version = "12";
    my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
    my $timestamp = sprintf ("%04d-%02d-%02d %02d.%02d.%02d", $year + 1900, $mon + 1, $mday, $hour, $min, $sec);
    my $githash = `git show-ref refs/heads/master`;
    # yields: "456def596d0e86726a714502ad0405016beb10c5 refs/heads/master\n"
    # $githash =~ s/\s.*//s; # remove all behind hash
    $githash = substr($githash, 0, 7);
    print <<"GFis";
# dbat/build.number generated by etc/util/update_version.pl

build.name=dbat
build.version=$major_version
build.number=$githash
build.date=$timestamp

GFis
__DATA__
#Fri, 04 Feb 2022 08:16:05 +0100

build.name=dbat
build.version=12
build.number=$githash
build.date=2022-02-04 08.16.05

