#!/usr/bin/perl

# postprocess data for parm_xref checking
# @(#) $Id$
# 2012-07-09: <var />
# 2012-01-18, Dr. Georg Fischer
#------------------------------------------------------------------ 
# Usage: c.f. makefile
#   perl parm_xref_post.pl x.tmp
#------------------------------------------------------------------------------- 
use strict;

    my $init = "INSERT INTO parm_xref(element, name, spec, file) VALUES (\'";
    my $sep  = "\',\'";
    my $term = "\');\n";
    my $rest;
    while (<>) {
        s{\s+\Z}{}; # chompr
        my $line = $_;
        if (0) {
        } elsif (m{\A\-\-}) {
            print "$line\n";
        } elsif (m{\A(parm|var|dbat|when)\t}) {
            my @fields = split(/\t/, $line);
            print $init . join($sep, @fields) . $term;
        } elsif (m{\A(input|select|textarea)\t}) {
            my @fields = split(/\t/, $line);
            $fields[0] = "input";
            print $init . join($sep, @fields) . $term;
        } elsif (m{\Ahref\t(\/dbat\/)?servlet\?\&?spec=(.*)}) {
            $rest = $2;
            &expand_link("link", $rest);
        } elsif (m{\Ahref\t([\w\_\-\/\.]+)\?\&?(.*)}) {
            $rest = "$1\&$2";
            &expand_link("link", $rest);
        } elsif (m{\Alink\t(.*)}) {
            $rest = $1;
            &expand_link("link", $rest);
        } else {
            print STDERR "unknown element in line: $line\n";
        }
    } # while <>

sub expand_link {
    my ($element, $rest) = @_; # ('link','test/selec01&alpha=&beta=&sp3=','','test/pivot03m.xml');
    my ($name, $spec, $file) = split(/\t/, $rest);
    $file =~ s{\.}{\/}g; # subdir "." back to "/"
    $name =~ s{\s}{}g; # remove whitespace in URL
    my @parms = map {
            s{\W\Z}{}; # remove trailing non-letter
            $_
            } split(/\&/, $name);
    $spec = shift(@parms);
    $spec =~ s{\.}{\/}g; # subdir "." back to "/"
    foreach $name (@parms) {
        print $init . join($sep, ($element, $name, $spec, $file)) . $term;
    } # foreach $parm
} # expand_link
__DATA__
# this is an example only

-- generated by etc/xslt/gen_parm_xref.xsl at 2012-01-18 21:09:25
INSERT INTO parm_xref(element, name, spec, file) VALUES ('href','/cgi-bin/im_diagram.pl&proc=&mode=&STATUS=&NAME=&dummy=','','test/im_grafik.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('href','/dbat/servlet?spec=spec3&prefix=','','test/rud.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('href','servlet?&spec=','','index.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('href','servlet?spec=spec1&prefix=&prefix2=','','test/selec02.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('href','servlet?spec=spec1&prefix=&prefix2=','','test/selec03.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('href','servlet?&spec=','','test/index.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('href','servlet?spec=test/selec01&name=','','test/pivot03.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('href','servlet?spec=test/selec01&name=','','test/pivot04.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('href','servlet?spec=test/selec01&name=&year=','','test/color04.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('href','servlet?spec=test/selec01&name*&year*','','test/selec02.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('href','servlet?spec=test/selec01&name*&year*','','test/selec03.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','birthchar','','test/listbox.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','birthint','','test/listbox.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','enrel','','test/ins1.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','entry','','test/ins1.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','morel','','test/ins1.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','morph','','test/ins1.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','name','','test/color04.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','name','','test/column02.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','name','','test/crud01.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','NAME','','test/im_diagram.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','NAME','','test/im_grafik.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','name','','test/modif01.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','name','','test/order01.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','name','','test/order02.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','name','','test/parmlink.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','name','','test/pivot03.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','name','','test/pivot04.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','name','','test/selec01.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','name','','test/selec02.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','name','','test/selec03.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','name','','test/selec04.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','part','','test/callproc.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','prefix','','test/rud.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','prefix','','test/with_cte.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','STATUS','','test/im_grafik.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','switch','','test/choose06.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','table','','describe.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('input','year','','test/parmlink.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('link','del1','','test/rud.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('link','spec1&prefix=&prefix2=','','test/selec02.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('link','spec1&prefix=&prefix2=','','test/selec03.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('link','spec2&prefix=','','test/rud.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('link','test.del1','','test/crud01.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('link','test.order02  &name=         &name=  ','','test/order01.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('link','test/selec01&alpha=&beta=&sp3=','','test/pivot03.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('link','test/selec01&alpha=&beta=&sp3=','','test/pivot04.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('link','test/selec01&year=&name=','','test/color04.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('link','test/selec01&year=&name=','','test/selec02.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('link','test/selec01&year=&name=','','test/selec03.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('link','test.upd1','','test/crud01.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('link','upd1','','test/rud.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','birthchar','','test/listbox.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','birthint','','test/listbox.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','enrel','','test/del1.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','enrel','','test/delx.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','enrel','','test/insx.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','entry','','test/del1.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','entry','','test/delx.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','entry','','test/insx.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','format','','test/im_grafik.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','morel','','test/insx.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','morph','','test/insx.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','namebox','','test/listbox.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','name','','test/column02.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','name','','test/crud01.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','NAME','','test/im_diagram.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','NAME','','test/im_grafik.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','name','','test/modif01.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','name','','test/order01.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','name','','test/order02.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','name','','test/parmlink.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','name','','test/selec01.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','name','','test/selec02.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','name','','test/selec03.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','name','','test/selec04.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','prefix','','test/rud.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','prefix','','test/with_cte.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','proc','','test/im_grafik.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','STATUS','','test/im_grafik.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','subdir','','index.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','table','','describe.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','wordlist','','test/textarea.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','WORDLIST','','test/textarea.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('parm','year','','test/parmlink.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('select','format','','test/im_grafik.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('select','namebox','','test/listbox.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('select','proc','','test/im_grafik.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('textarea','wordlist','','test/textarea.xml');
INSERT INTO parm_xref(element, name, spec, file) VALUES ('textarea','WORDLIST','','test/textarea.xml');
commit;
