-- SQL generated by Dbat on yyyy-mm-dd hh:mm:ss
-- MySQL 5.1.62-0ubuntu0.11.10.1 with MySQL-AB JDBC Driver mysql-connector-java-5.1.11 ( Revision: ${svn.Revision} )
DROP   VIEW vw1;
CREATE VIEW vw1
	( name	VARCHAR(16) NOT NULL -- Name of the Relative
	, birth	DATE
	);
COMMIT;
